package flake

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/BuilderHub/deps2flake/internal/scaffold"
)

// GoData is the render model for a Go project flake.
type GoData struct {
	PackageName      string
	ModulePath       string
	GoVersion        string
	IncludeContainer bool
	scaffold.GoOptions
}

// WriteGo renders and writes a Go flake.
func WriteGo(path string, data GoData, force bool) error {
	if err := EnsureWritable(path, force); err != nil {
		return err
	}

	rendered, err := renderGo(data)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}
	if err := os.WriteFile(path, rendered, 0644); err != nil {
		return fmt.Errorf("writing flake: %w", err)
	}
	return nil
}

func renderGo(data GoData) ([]byte, error) {
	if data.PackageName == "" {
		return nil, fmt.Errorf("package name is required")
	}
	if err := scaffold.ValidateGoCompiler(data.Compiler); err != nil {
		return nil, err
	}
	if len(data.SubPackages) == 0 {
		data.SubPackages = []string{"./"}
	}

	cleanDeriv := make([]string, 0, len(data.DerivationArgs))
	for _, line := range data.DerivationArgs {
		line = strings.TrimSpace(line)
		if line != "" {
			cleanDeriv = append(cleanDeriv, line)
		}
	}
	data.DerivationArgs = cleanDeriv

	normalizeGoDataLists(&data)

	var buf bytes.Buffer
	if err := goTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering flake: %w", err)
	}
	return buf.Bytes(), nil
}

func normalizeGoDataLists(data *GoData) {
	if len(data.Ldflags) == 0 {
		data.Ldflags = nil
	}
	if len(data.Tags) == 0 {
		data.Tags = nil
	}
	if len(data.CheckFlags) == 0 {
		data.CheckFlags = nil
	}
	if strings.TrimSpace(data.CGOEnabled) == "" {
		data.CGOEnabled = ""
	}
	if strings.TrimSpace(data.GOOS) == "" {
		data.GOOS = ""
	}
	if strings.TrimSpace(data.GOARCH) == "" {
		data.GOARCH = ""
	}
	if strings.TrimSpace(data.Compiler) == "" {
		data.Compiler = ""
	}
}

func nixString(value string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(value); i++ {
		switch value[i] {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '$':
			if i+1 < len(value) && value[i+1] == '{' {
				b.WriteString(`\$`)
				continue
			}
			b.WriteByte(value[i])
		default:
			b.WriteByte(value[i])
		}
	}
	b.WriteByte('"')
	return b.String()
}

// nixHookString returns a Nix indented string literal (” ... ”) with user bash escaped.
func nixHookString(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "''"
	}
	escaped := strings.ReplaceAll(value, "${", "''${")
	escaped = strings.ReplaceAll(escaped, "'", "''")
	var b strings.Builder
	b.WriteString("''\n")
	for _, line := range strings.Split(escaped, "\n") {
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("''")
	return b.String()
}

var goTemplate = template.Must(template.New("go-flake").Funcs(template.FuncMap{
	"nixString":     nixString,
	"nixHookString": nixHookString,
}).Parse(`{
  description = "{{ .PackageName }} generated by deps2flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    nopher.url = "github:anthr76/nopher";
  };

  outputs = { self, nixpkgs, flake-utils, nopher }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        nopherLib = nopher.lib.${system};

        app = nopherLib.buildNopherGoApp {
          pname = "{{ .PackageName }}";
          version = "0.1.0";
          src = ./.;
          modules = ./nopher.lock.yaml;
          subPackages = [{{ range .SubPackages }} "{{ . }}"{{ end }} ];
{{- if .Compiler }}
          go = {{ .Compiler }};
{{- end }}
{{- if .Ldflags }}
          ldflags = [{{ range .Ldflags }} {{ nixString . }}{{ end }} ];
{{- end }}
{{- if .Tags }}
          tags = [{{ range .Tags }} {{ nixString . }}{{ end }} ];
{{- end }}
{{- if .CGOEnabled }}
          CGO_ENABLED = {{ nixString .CGOEnabled }};
{{- end }}
{{- if .GOOS }}
          GOOS = {{ nixString .GOOS }};
{{- end }}
{{- if .GOARCH }}
          GOARCH = {{ nixString .GOARCH }};
{{- end }}
{{- if .SkipCheck }}
          doCheck = false;
{{- end }}
{{- if .CheckFlags }}
          checkFlags = [{{ range .CheckFlags }} {{ nixString . }}{{ end }} ];
{{- end }}
{{- if .PreBuild }}
          preBuild = {{ nixHookString .PreBuild }};
{{- end }}
{{- if .PostBuild }}
          postBuild = {{ nixHookString .PostBuild }};
{{- end }}
{{- if .PreCheck }}
          preCheck = {{ nixHookString .PreCheck }};
{{- end }}
{{- if .PostCheck }}
          postCheck = {{ nixHookString .PostCheck }};
{{- end }}
{{- if .PreInstall }}
          preInstall = {{ nixHookString .PreInstall }};
{{- end }}
{{- if .PostInstall }}
          postInstall = {{ nixHookString .PostInstall }};
{{- end }}
{{- range .DerivationArgs }}
          {{ . }}
{{- end }}

          meta = {
            description = "{{ .ModulePath }}";
            mainProgram = "{{ .PackageName }}";
          };
        };
      in
      {
        packages = {
          default = app;
{{- if .IncludeContainer }}
          container = pkgs.dockerTools.buildLayeredImage {
            name = "{{ .PackageName }}";
            tag = "latest";
            contents = [ app ];
            config = {
              Cmd = [ "${app}/bin/{{ .PackageName }}" ];
            };
          };
{{- end }}
        };

        apps.default = {
          type = "app";
          program = "${app}/bin/{{ .PackageName }}";
        };

        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.go
            app
          ];
        };
      });
}
`))
