package flake

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// GoData is the render model for a Go project flake.
type GoData struct {
	PackageName      string
	ModulePath       string
	GoVersion        string
	SubPackages      []string
	IncludeContainer bool
}

// WriteGo renders and writes a Go flake.
func WriteGo(path string, data GoData, force bool) error {
	if err := EnsureWritable(path, force); err != nil {
		return err
	}

	rendered, err := renderGo(data)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}
	if err := os.WriteFile(path, rendered, 0644); err != nil {
		return fmt.Errorf("writing flake: %w", err)
	}
	return nil
}

func renderGo(data GoData) ([]byte, error) {
	if data.PackageName == "" {
		return nil, fmt.Errorf("package name is required")
	}
	if len(data.SubPackages) == 0 {
		data.SubPackages = []string{"./"}
	}

	var buf bytes.Buffer
	if err := goTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering flake: %w", err)
	}
	return buf.Bytes(), nil
}

var goTemplate = template.Must(template.New("go-flake").Parse(`{
  description = "{{ .PackageName }} generated by deps2flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    nopher.url = "github:anthr76/nopher";
  };

  outputs = { self, nixpkgs, flake-utils, nopher }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        nopherLib = nopher.lib.${system};

        app = nopherLib.buildNopherGoApp {
          pname = "{{ .PackageName }}";
          version = "0.1.0";
          src = ./.;
          modules = ./nopher.lock.yaml;
          subPackages = [{{ range .SubPackages }} "{{ . }}"{{ end }} ];

          meta = {
            description = "{{ .ModulePath }}";
            mainProgram = "{{ .PackageName }}";
          };
        };
      in
      {
        packages = {
          default = app;
{{- if .IncludeContainer }}
          container = pkgs.dockerTools.buildLayeredImage {
            name = "{{ .PackageName }}";
            tag = "latest";
            contents = [ app ];
            config = {
              Cmd = [ "${app}/bin/{{ .PackageName }}" ];
            };
          };
{{- end }}
        };

        apps.default = {
          type = "app";
          program = "${app}/bin/{{ .PackageName }}";
        };

        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.go
            app
          ];
        };
      });
}
`))
