package flake

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/BuilderHub/deps2flake/internal/scaffold"
)

// PythonData is the render model for a Python project flake.
type PythonData struct {
	PackageName      string
	ProjectName      string
	ProjectVersion   string
	PythonVersion    string
	MainProgram      string
	IncludeContainer bool
	WrapApp          bool
	scaffold.PythonOptions
}

func pythonAppNeedsWrapper(data PythonData) bool {
	if data.SkipCheck || len(data.CheckFlags) > 0 || len(data.DerivationArgs) > 0 {
		return true
	}
	for _, hook := range []string{
		data.PreBuild, data.PostBuild, data.PreCheck, data.PostCheck, data.PreInstall, data.PostInstall,
	} {
		if strings.TrimSpace(hook) != "" {
			return true
		}
	}
	return false
}

// WritePython renders and writes a Python flake.
func WritePython(path string, data PythonData, force bool) error {
	if err := EnsureWritable(path, force); err != nil {
		return err
	}

	rendered, err := renderPython(data)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}
	if err := os.WriteFile(path, rendered, 0644); err != nil {
		return fmt.Errorf("writing flake: %w", err)
	}
	return nil
}

func renderPython(data PythonData) ([]byte, error) {
	if data.PackageName == "" {
		return nil, fmt.Errorf("package name is required")
	}
	if data.MainProgram == "" {
		data.MainProgram = data.PackageName
	}
	if err := scaffold.ValidatePythonInterpreter(data.Interpreter); err != nil {
		return nil, err
	}
	if err := scaffold.ValidatePythonSourcePreference(data.SourcePreference); err != nil {
		return nil, err
	}

	cleanDeriv := make([]string, 0, len(data.DerivationArgs))
	for _, line := range data.DerivationArgs {
		line = strings.TrimSpace(line)
		if line != "" {
			cleanDeriv = append(cleanDeriv, line)
		}
	}
	data.DerivationArgs = cleanDeriv

	if data.SourcePreference == "" {
		data.SourcePreference = "wheel"
	}

	normalizePythonDataLists(&data)
	data.WrapApp = pythonAppNeedsWrapper(data)

	var buf bytes.Buffer
	if err := pythonTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering flake: %w", err)
	}
	return buf.Bytes(), nil
}

func normalizePythonDataLists(data *PythonData) {
	if len(data.Scripts) == 0 {
		data.Scripts = nil
	}
	if len(data.CheckFlags) == 0 {
		data.CheckFlags = nil
	}
	if strings.TrimSpace(data.Interpreter) == "" {
		data.Interpreter = ""
	}
}

var pythonTemplate = template.Must(template.New("python-flake").Funcs(template.FuncMap{
	"nixString":     nixString,
	"nixHookString": nixHookString,
}).Parse(`{
  description = "{{ .PackageName }} generated by deps2flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    pyproject-nix = {
      url = "github:pyproject-nix/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    uv2nix = {
      url = "github:pyproject-nix/uv2nix";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    pyproject-build-systems = {
      url = "github:pyproject-nix/build-system-pkgs";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.uv2nix.follows = "uv2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, pyproject-nix, uv2nix, pyproject-build-systems }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        lib = nixpkgs.lib;

        python =
{{- if .Interpreter }}
          {{ .Interpreter }};
{{- else }}
          pkgs.python3;
{{- end }}

        workspace = uv2nix.lib.workspace.loadWorkspace { workspaceRoot = ./.; };

        overlay = workspace.mkPyprojectOverlay {
          sourcePreference = {{ nixString .SourcePreference }};
        };

        pythonSet =
          (pkgs.callPackage pyproject-nix.build.packages {
            inherit python;
          }).overrideScope (
            lib.composeManyExtensions [
              pyproject-build-systems.overlays.wheel
              overlay
            ]
          );

        appEnv = pythonSet.mkVirtualEnv "{{ .PackageName }}-env" workspace.deps.default;

{{- if .WrapApp }}
        app = pkgs.stdenv.mkDerivation {
          pname = "{{ .PackageName }}";
          version = {{ nixString .ProjectVersion }};
          src = ./.;
          buildInputs = [ appEnv ];
          dontConfigure = true;
{{- if .SkipCheck }}
          doCheck = false;
{{- end }}
{{- if .CheckFlags }}
          checkFlags = [{{ range .CheckFlags }} {{ nixString . }}{{ end }} ];
{{- end }}
{{- if .PreBuild }}
          preBuild = {{ nixHookString .PreBuild }};
{{- end }}
{{- if .PostBuild }}
          postBuild = {{ nixHookString .PostBuild }};
{{- end }}
{{- if .PreCheck }}
          preCheck = {{ nixHookString .PreCheck }};
{{- end }}
{{- if .PostCheck }}
          postCheck = {{ nixHookString .PostCheck }};
{{- end }}
{{- if .PreInstall }}
          preInstall = {{ nixHookString .PreInstall }};
{{- end }}
{{- if .PostInstall }}
          postInstall = {{ nixHookString .PostInstall }};
{{- end }}
{{- range .DerivationArgs }}
          {{ . }}
{{- end }}
          installPhase = ''
            mkdir -p $out/bin
            cp -r ${appEnv}/bin/* $out/bin/ 2>/dev/null || true
          '';
          meta = {
            description = {{ nixString .ProjectName }};
            mainProgram = {{ nixString .MainProgram }};
          };
        };
{{- else }}
        app = appEnv;
{{- end }}
{{- if .IncludeContainer }}
        linuxSystem =
          if system == "aarch64-darwin" then "aarch64-linux"
          else if system == "x86_64-darwin" then "x86_64-linux"
          else system;
        appLinux =
          if linuxSystem == system then app
          else
            let
              pkgsLinux = nixpkgs.legacyPackages.${linuxSystem};
              pythonLinux =
{{- if .Interpreter }}
                {{ .Interpreter }};
{{- else }}
                pkgsLinux.python3;
{{- end }}
              workspaceLinux = uv2nix.lib.workspace.loadWorkspace { workspaceRoot = ./.; };
              overlayLinux = workspaceLinux.mkPyprojectOverlay {
                sourcePreference = {{ nixString .SourcePreference }};
              };
              pythonSetLinux =
                (pkgsLinux.callPackage pyproject-nix.build.packages {
                  inherit pythonLinux;
                }).overrideScope (
                  lib.composeManyExtensions [
                    pyproject-build-systems.overlays.wheel
                    overlayLinux
                  ]
                );
              appEnvLinux = pythonSetLinux.mkVirtualEnv "{{ .PackageName }}-env" workspaceLinux.deps.default;
            in
            appEnvLinux;
{{- end }}
      in
      {
        packages = {
          default = app;
{{- if .IncludeContainer }}
          container = pkgs.dockerTools.buildLayeredImage {
            name = "{{ .PackageName }}";
            tag = "latest";
            contents = [ appLinux ];
            config = {
              Cmd = [ "${appLinux}/bin/{{ .MainProgram }}" ];
            };
          };
{{- end }}
        };

        apps.default = {
          type = "app";
          program = "${app}/bin/{{ .MainProgram }}";
        };

        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.uv
            app
          ];
          env = {
            UV_NO_SYNC = "1";
            UV_PYTHON = pythonSet.python.interpreter;
            UV_PYTHON_DOWNLOADS = "never";
          };
        };
      });
}
`))
